### ISSUE TITLE
Use environmental variables in password

### ISSUE THREAD

**Issue by AGSCL** [mattwarkentin/fidelius#10]
Is it possible to use `'`r Sys.getenv("CANVASPASS")`'` or  `"`r as.character(read.table('H:/Mi unidad/Curso_UDP/pass_canvas.txt', quote='\"', comment.char=''))"' ` in password YAML?

output:
  fidelius::html_password_protected:
    style:
      button_text: "Ingresar clave"
    password: '`r Sys.getenv("CANVASPASS")`'
    preview: false
    hint: ""
    bundle: true
    output_format: 
      rmarkdown::html_document:
        toc: true # table of content true
        toc_depth: 5  # upto three depths of headings (specified by #, ## and ###)
        toc_float: true

**Comment by mattwarkentin** [comment]
Hi @AGSCL,

I think this should be possible with something like:
````yaml
---
output:
  fidelius::html_password_protected:
    password: `r Sys.getenv('CANVASPASS')`
    output_format: rmarkdown::html_document
---
````

Let me know if this does not work for you.
