### ISSUE TITLE
Is it possible to add parameters to the YAML???

### ISSUE THREAD

**Issue by AGSCL** [mattwarkentin/fidelius#6]
For example, I have the following YAML:
---
title: "Analisis Joel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide  
    toc: true # table of content true
    toc_depth: 4  # upto three depths of headings (specified by #, ## and ###)
    toc_float: true
---

But I want to add these parameters to the YAML using `fidelius`:

---
title: "RDS Katherine"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  code_folding: true
  fidelius::html_password_protected:
    password: "katherine"
    hint: "tu nombre en minúsculas"
---

**Comment by AGSCL** [comment]
I followed the instructions and i solved it:
```

---
title: "RDS Katherine"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  fidelius::html_password_protected:
    style:
      button_text: "Ingresar clave"
    password: "katherine"
    hint: "tu nombre en minúsculas"
    output_format: 
      rmarkdown::html_document:
        code_folding: hide  
        toc: true # table of content true
        toc_depth: 4  # upto three depths of headings (specified by #, ## and ###)
        toc_float: true
---
```
